export * as AuthService from './auth.service'
export * as UserService from './user.service'
export * as ReviewService from './review.service'
export * as InquiryService from './inquiry.service'
export * as AppointmentService from './appointment.service'
export * as NewsService from './news.service'
