import '@/styles/normalize.css'
import '@/styles/palette.css'
import '@/styles/global.css'

import './layout.css'
import { Footer, Navs } from './components'
import { getTitle } from '@/constants'
import { Metadata } from 'next'
import { Public_Sans, EB_Garamond } from 'next/font/google'
import Script from 'next/script'

export const metadata: Metadata = {
  title: getTitle(),
  description: 'Generated by create next app',
}

const publicSans = Public_Sans({ subsets: ['latin'] })
const ebGaramond = EB_Garamond({ subsets: ['latin'] })

const Layout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html lang="es">
    <body
      style={{
        '--pal-font-a': publicSans.style.fontFamily,
        '--pal-font-b': ebGaramond.style.fontFamily,
      }}
    >
      <Navs />
      <main>{children}</main>
      <Footer />
    </body>
    <Script src="https://kit.fontawesome.com/7463805de7.js" />
  </html>
)

export default Layout
